name: road_condition_mapping
description: Mobile Application for Road Condition Detection with Computer Vision
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  path_provider: ^2.0.14
  galleryimage: ^1.2.0
  camera: any
  camerawesome: ^1.3.0
  path: any
  geolocator: ^9.0.2
  geocode: 1.0.1
  geocoding: ^2.0.4
  location: ^4.2.0
  search_map_place_updated: ^0.0.4
  http: ^0.13.6
  uuid: ^3.0.5
  persistent_bottom_nav_bar: any
  flutter_secure_storage: ^8.0.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  auth0_flutter: ^1.1.0
  latlong2: ^0.8.0
  flutter_map: ^4.0.0
  custom_info_window: ^1.0.1
  url_launcher: ^6.1.11
  contactus: ^1.2.3
  font_awesome_flutter: ^10.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true
  assets:
    - assets/

